### ISSUE TITLE
Add buttons to select shelter pokemon

### ISSUE THREAD

**Issue by jpgualdarrama** [jpgualdarrama/PokeFarmQoL#22]
Add capability to use number buttons to select which pokemon from the shelter to adopt instead of having to click. For some context, I thought of this when I was searching for something in the shelter with both hands on the keyboard and thought that it would be faster to be able to use the keyboard instead of moving my hand to the mouse to click on the pokemon.

(No post to link, since this one came from me)

**Comment by bobpaw** [comment]
I assume you mean from a list of found Pokémon, but how would that work for cases where more than 10 matches were found?

**Comment by jpgualdarrama** [comment]
I was actually thinking of using two sequential numbers to select a single Pokemon/Egg by using the first number as a row and the second number as a column. After entering both numbers, the Pokemon/Egg at that row and column would be selected. Of course, this would only work when the grid layout is being used

**Comment by bobpaw** [comment]
That does sound pretty good. Pokefarm users love efficiency, myself included, and the shelter is one of the few places I have to use a mouse. It should be said that in fields and multiuser pages selecting any QoL options causes A and D hotkeys to break,

**Comment by bobpaw** [comment]
I realized that 1, 2, and 3 are already hotkeys for reload, white, and black flutes, respectively (as well as shift plus the numbers). This means selecting a pokemon would require a key before to enter selection mode. Unrelated, the code for hotkeying those buttons is very easy to copy and paste if users wish for a different hotkey, like more intuitive r/w/b.

**Comment by jpgualdarrama** [comment]
I've been thinking about this, and I would rather not change the existing hot keys. But on the other hand, I also can't think of an intuitive set of keys to use for selecting a pokemon in the shelter that isn't the number keys. I thought of using the arrow keys to move left, right, up, and down among the pokemon, that but would of course conflict with the arrow keys being used by the browser for scrolling.

I'm going to mark this as on hold and help wanted.

**Comment by pbabbicola** [comment]
what about "tabbing" through them with a letter?

**Comment by jpgualdarrama** [comment]
@pbabbicola That's a good idea. We could use 'r' to tab through the rows and 'c' to tab through the columns.

**Comment by pbabbicola** [comment]
I would directly just cycle through them with one key. You normally have 3-4 matches per page at least with how I use it.

**Comment by jpgualdarrama** [comment]
Ah okay, I was thinking of cycling through all the pokemon in the shelter field, not just the matches. I think as a default 'n' for "next" would be an okay choice. (One of the other issues #28 will make this customizable)

**Comment by jpgualdarrama** [comment]
Design Notes:
- How to click on one of the matches in the shelter:
   `$('#shelterarea').find('.pokemon').find('.shelterfoundme').parent().eq(0).trigger('click')`
- The user **must** click the key to select the first match. Auto-selecting the first match would definitely be close (if not would be) cheating

**Comment by jpgualdarrama** [comment]
This was actually promoted 4 days ago - no issues reported; closing
