### ISSUE TITLE
Private field search and release select all are mutually inclusive

### ISSUE THREAD

**Issue by bobpaw** [jpgualdarrama/PokeFarmQoL#33]
You cannot enable release/fishing select all while disabling private field search without breaking private field search functionality.

**Comment by jpgualdarrama** [comment]
A year later, it just clicked in my brain what this. Going to start working it

**Comment by jpgualdarrama** [comment]
Thinking about creating more granular 'enable/disable' settings for all pages:
- Daycare
  - The only feature here is the pokemon highlighting when searching for a mon to put in the daycare. One enable/disable setting in the QoL Hub is sufficient.
- Dex
  - Only feature here is the additional type filtering button. One enable/disable setting in the QoL Hub is sufficient.
- Farm
  - There are three sorting options here, but the controls are unobtrusive. One enable/disable setting in the QoL Hub is sufficient.
- Fishing
  - The only feature on this page is the ability to select pokemon by berry or "all".  One enable/disable setting in the QoL Hub is sufficient.
- Lab
  - Egg type and egg custom search both already have settings on the page.  One enable/disable setting in the QoL Hub is sufficient.
- Multiuser
  - Only feature here is the hide buttons.  One enable/disable setting in the QoL Hub is sufficient.
- Private Fields
  - Three features: Tooltip controls, Searching, and Release controls. Can add a enable/disable setting for each of these.
- Public Fields
  - Four features: Tooltip controls, Searching, Sorting, and Release controls. Can add a enable/disable setting for each of these.
- Shelter
  - The Shelter has Search and Sort features. Can add a enable/disable setting for each of these.
- Wishforge
  - Only feature here is the Crafted Badges reformatting. One enable/disable setting in the QoL Hub is sufficient.

**Comment by jpgualdarrama** [comment]
![image](https://user-images.githubusercontent.com/7121719/125181647-f1254500-e1d4-11eb-87d9-59fa859a9e42.png)
