### ISSUE TITLE
Tooltips aren't disabled with use of hotkeys

### ISSUE THREAD

**Issue by bobpaw** [jpgualdarrama/PokeFarmQoL#40]
Hotkeys tend to screw up the entire UserScript up. In yet another thrilling episode, the evil tooltip rears it's head for one last battle! We learn that when hotkeys, magical spells which grant speed and efficiency, are utilized by many of the region's denizens. However! Our courageous heroes are themselves afraid of hotkeys! Mages have recently been using hotkeys, and have reawoken the foe our heroes finally thought vanquished. What will they do?

tl;dr using hotkeys doesn't activate the removal of tooltips with berries on. The keys are 12345, and their respective numpad keys. 
[these lines](https://github.com/jpgualdarrama/PokeFarmQoL/blob/c7cce542e00718d8f8d3010be5f53c8e2e91ae52/requires/publicFieldsPage.js#L212-L222) are the ones that need to be duplicated with the trigger changed to be tooltip disable. The function should looks something like this:
    
    $(window).on('keyup.field_shortcuts', function (a) {
      if (0 == $(a.target).closest('input, textarea').length) {
        var b = function (c) {
          g && g == c.data('berry') ? (c = document.elementFromPoint(C - document.documentElement.scrollLeft - document.body.scrollLeft, D - document.documentElement.scrollTop - document.body.scrollTop), c = $(c).closest('.fieldmon'), c.length && (a.preventDefault(), y(c, a)))  : c.trigger('mousedown')
        };
        switch (a.keyCode) {
          case 37:
          case 65:
            $('#field_nav [data-action=previous]').trigger('click');
            break;
          case 39:
          case 68:
            $('#field_nav [data-action=next]').trigger('click');
            break;
          case 49:
          case 97:
            b(k.find('a').eq(0));
            break;
          case 50:
          case 98:
            b(k.find('a').eq(1));
            break;
          case 51:
          case 99:
            b(k.find('a').eq(2));
            break;
          case 52:
          case 100:
            b(k.find('a').eq(3));
            break;
          case 53:
          case 101:
            b(k.find('a').eq(4))
        }
      }
    });
Which I copied from the Pokéfarm page. Those are the correct keycodes, but function `b` definitely isn't necessary.

**Comment by jpgualdarrama** [comment]
Note to self - steps to test:
1. Disable "Hide when berry selected".
2. Enable "Hide when berry selected".
3. Refresh page.
4. Use hotkey (1-5) to select berry.
5. Check if tooltips appear or not

**Comment by jpgualdarrama** [comment]
Verified that changes on issue_40 branch fix the issue and that in step 5 of my previous comment, the tooltips are not shown.

**Comment by jpgualdarrama** [comment]
No issues reported; closing
